name: Deploy React App to GitHub Pages

on:
  push:
    branch:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:  
        working-directory: my-app

  step:
    - name: Checkput repo
      uses: action/checkout@v3

    - name: Sey up Node.js
      uses: actions/setup-node@v3
      with:
        node-cersion: '18'

    - name: Install dependencies
      run: npm install
    
    - name: Build project
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/action-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: my-app/build